$env:GOV_SM4_KEY='1234567812345678'
$env:GOV_PASSWORD_PEPPER='pepper_for_bootstrap_e2e'
$env:GOV_DB_URL='jdbc:mariadb://localhost:13306/gov_db_bootstrap_e2e?useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_unicode_ci&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&useInformationSchema=true'
$env:GOV_DB_USERNAME='db_user'
$env:GOV_DB_PASSWORD='Egov@123'
$env:GOV_MINIO_ENDPOINT='http://127.0.0.1:9000'
$env:GOV_MINIO_PUBLIC_ENDPOINT='http://127.0.0.1:9000'
$env:GOV_MINIO_ACCESS_KEY='govadmin'
$env:GOV_MINIO_SECRET_KEY='govadminpassword'
$env:GOV_BOOTSTRAP_ENABLED='true'
$env:GOV_BOOTSTRAP_FORCE_RESET_ADMIN_ON_FIRST_START='true'
$env:GOV_BOOTSTRAP_ADMIN_USERNAME='admin'
$env:GOV_BOOTSTRAP_ADMIN_INITIAL_PASSWORD='admin123'
Set-Location 'C:\Users\brace\Documents\gov-project\gov-project-backend'
mvn spring-boot:run
